### PR TITLE
Add Items to Works in MiroTransformable

### PR DESCRIPTION
**Pull request by kenoir**
### What is this PR trying to achieve?

Ingest Items on Works for Miro data.

### Who is this change for?

💻  & 📚 

### Have the following been considered/are they needed?

- [ ] Deployed new versions

### CODE REVIEW

**Comment by kenoir** [comment]
For https://github.com/wellcometrust/platform-api/issues/573

**Comment by alexwlchan** [comment]
What you’ve got looks good. Any tests? And does it matter that we won’t be adding any canonical IDs to these items?

**Comment by kenoir** [comment]
> And does it matter that we won’t be adding any canonical IDs to these items?
Yes it does matter.

> Any tests?
There are already tests which cover this functionality (but as I forgot to actually add items to works they haven't needed to be updated).

**Comment by alexwlchan** [comment]
Also, having the different bits of transformer logic in different methods makes these patches much cleaner, I like.

**Pull request merged**
