### PR TITLE
transformer with extra 🐍

### PR DESCRIPTION
**Pull request by alexwlchan**
I was getting a bit frustrated with the Scala transformer, so I knocked up a Python-based transformer on my lunch break. We probably shouldn’t abandon Scala at this stage, but putting it out there to see what people think.

### CODE REVIEW

**Comment by alexwlchan** [comment]
Things that are missing, among others:

* Packaging
* Error handling – any exception will tear down the entire process
* Tests

**Comment by kenoir** [comment]
I think as this is transforming to a type shared by other apps this should definitely be Scala.

**Comment by alicefuzier** [comment]
@kenoir I agree, but shouldn't you be on holiday??

**Comment by kenoir** [comment]
I'm just contributing to an interesting open source project! Very relaxing.

**Pull request closed without merging**
