### PR TITLE
Add Travis build badge

### PR DESCRIPTION
**Pull request by kenoir**
## What is this PR trying to achieve?

Explicitly show project build status.

## Who is this change for?

Folk interested in whether the most recent version of `master` is passing its' build.

## Have the following been considered/are they needed?

- [X] Tests?
- [X] Docs?
- [X] Spoken to the right people?

### CODE REVIEW

**Comment by alexwlchan** [comment]
Personally not a fan of build badges – I think they look ugly, and really master should never be failing.

But I don't care strongly enough to argue if you and @alicefuzier disagree.

**Comment by kenoir** [comment]
> and really master should never be failing.

Exactly, _but it can_.

**Comment by kenoir** [comment]
Pinging @jtweed as this is a public perception thing too.

**Comment by jtweed** [comment]
I quite like it, I think it shows that we care that the build is always passing. That's a positive perception, provided the build is always passing of course!

**Pull request merged**
