### PR TITLE
JSON book example

### PR DESCRIPTION
**Pull request by ChristopherHilton**
### What is this PR trying to achieve?
Removal of comments into Markdown, correction of JSON errors
### Who is this change for?
Platform team

### CODE REVIEW

**Comment by alexwlchan** [comment]
This doesn’t look right to me – the comments in the Markdown file don’t go with this JSON file.

This is probably going to be easier to work through in person – @ChristopherHilton, let’s sit down tomorrow and work through the pile of patches together. Content all looks good, but making sure they’re easily reviewable is important too. 😄

**Comment by ChristopherHilton** [comment]
Grand, thanks: I was thinking as I put this blizzard of stuff in that it could do with being neatly organised so that JSON and comments are easily linked.  I’m writing up a Library blog thing at home today but let’s talk about it on Monday?
Chris

**Comment by alexwlchan** [comment]
> I’m writing up a Library blog thing at home today but let’s talk about it on Monday?

Sounds good to me!

**Comment by ChristopherHilton** [comment]
BTW, while this is fresh in my mind I noticed yesterday that I’d put the JSON Sierra Book sample (https://github.com/wellcometrust/platform-api/blob/master/Sierra_book.json) into the master top-level repository rather than the Ontologies folder - would be useful to shift this as part of the same chat.  (The mapping of the repository onto my shared O drive doesn’t update, so I don’t have the option of shifting it via Windows Explorer without a long preceding dialogue with IT – if there are ways within Github of moving it that sounds a lot simpler.)
Chris

**Pull request merged**
