### PR TITLE
Fix transformer build

### PR DESCRIPTION
**Pull request by alicefuzier**
I _think_ transformer build is broken on master because of an error in our makefile. FIxing it but firste I'm triggering a rebuild of the transformer to make sure

### CODE REVIEW

**Comment by alexwlchan** [comment]
Oops.

🙈

**Comment by alexwlchan** [comment]
(This is why I shouldn't edit code on my phone!)

**Comment by pollecuttn** [comment]
... during leave! We can see you!

**Comment by alexwlchan** [comment]
I was still in the building when I made that code change yesterday, totes doesn't count

**Pull request merged**
