### PR TITLE
Consolidate certificates into the ALB module

### PR DESCRIPTION
**Pull request by alexwlchan**
WIP.

### CODE REVIEW

**Comment by kenoir** [comment]
Good idea to consolidate certs with ALBs.

**Comment by alexwlchan** [comment]
Not entirely sure it’s worked yet, actual aim here is to get HTTP ~> HTTPS redirect working. 😛

**Comment by kenoir** [comment]
The consolidation is a PR in its' own right :)

**Comment by kenoir** [comment]
Google provides! http://scottwb.com/blog/2013/10/28/always-on-https-with-nginx-behind-an-elb/

**Comment by alexwlchan** [comment]
This actually plans on its own now, so let’s get this in while I continue fiddling with HTTP and HTTPS stuff. 😄

**Pull request merged**
