### PR TITLE
[WIP] Try to get faster builds

### PR DESCRIPTION
**Pull request by alexwlchan**
### What is this PR trying to achieve?

Make our builds go faster!

### Who is this change for?

Bored developers!

---

Notes:

* Trashing the `common/target` and `~/.ivy2` directories on my local machine causes a compile to go from 22s to 446s (!!).

### CODE REVIEW

**Comment by alexwlchan** [comment]
Plan is to get a couple of runs of a complete build on Circle to see if this makes a difference, and merge if it does.

**Comment by alexwlchan** [comment]
Initial two runs, we save about 6 minutes from caching.

Some other ideas:

* Cache the Docker images used in the tests
* Don’t stop and restart the Docker containers between tasks
* Don’t run a stack of separate sbt tasks each time; we’re paying the cost of starting the JVM multiple times

**Comment by alexwlchan** [comment]
Take advantage of Circle’s parallelism?

**Comment by kenoir** [comment]
If we intend to move to Jenkins, we should try and make sure changes here are portable.

**Comment by alexwlchan** [comment]
Superseded by #188.

**Pull request closed without merging**
